food/urls.py
from django.urls import path
from . import views


app_name='food'
urlpatterns = [
    path('', views.index, name='index'),
    path('items/', views.items, name='items'),
    path('detail/<int:pk>/', views.detail, name='detail'),

    # //add item
    # path('add/', views.create_item, name='create_item'),
    path('add/', views.CreateItem.as_view(), name='create_item'),
    path('update/<int:pk>/', views.update_item, name='update_item'),
    path('delete/<int:pk>/', views.delete_item, name='delete_item'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('', include('users.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
      path('register/', views.register, name='register'),
      path('login/', views.login_view, name='login'),
      path('logout/', views.logout_view, name='logout'),
      path('profile/', views.profile_page, name='profile')
]

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Item(models.Model):
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="https://www.cvent.com/sites/default/files/styles/focus_scale_and_crop_800x450/public/migrated_attachments/meal-918638_1280-1.jpg?itok=dMJGxEC2")
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    def __str__(self):
        return self.item_name

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})
    

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg', upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

food/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import Item
from .forms import ItemForm
from django.views.generic.edit import CreateView
# Create your views here.

def index(request):
    item_list = Item.objects.all()
    context = {
        'item_list':item_list
    }
    return render(request, 'index.html', context)

def items(request):
    return HttpResponse("This is item")


def detail(request, pk):
    item = Item.objects.get(id= pk)
    context = {
        'item':item
    }
    return render(request, 'detail.html', context)

def create_item(request):
    form = ItemForm(request.POST or None)
    context={'form':form}

    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request, 'item-form.html', context)

#this is a class based view for create item
class CreateItem(CreateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'item-form.html'
    def form_valid(self, form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)



def update_item(request, pk):
    item = Item.objects.get(id=pk)
    form = ItemForm(request.POST or None, instance=item)
    context = {'form':form, 'item':item}
    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'item-form.html', context )

def delete_item(request, pk):
    item = Item.objects.get(id=pk)
    context = {'item':item}
    if request.method == 'POST':
        item.delete()
        return redirect('food:index')

    return render(request, 'item-delete.html', context)

users/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import RegisterForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm

# Create your views here.


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"Welcome {username}, Your account is created")
            return redirect('users:login')
    else:
      form = RegisterForm()
    context = {'form':form}
    return render(request, 'register.html', context)


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("food:index")
            else:
                messages.error(request,"Invalid username or password.")
        else:
            messages.error(request,"Invalid username or password.")
    form = AuthenticationForm()
    context = {'form':form}
    return render(request, 'login.html', context)

def logout_view(request):
    logout(request)
    return render(request, 'logout.html')

@login_required(login_url='/login')
def profile_page(request):

    return render(request, 'profile.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel ="stylesheet" href="{% static 'css/styles.css' %}" >
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">FoodApp</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'food:create_item' %}">Add Item</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Delete Item</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">View Item</a>
              </li>
              <li class="nav-item">
                {% if user.is_authenticated %}
                  <a href="{% url 'users:logout' %}" class="nav-link">Logout</a>
                  <li class="nav-item">
                  <a href="{% url 'users:profile' %}" class="nav-link">Profile</a>
                </li>
                {% else %}
                 <a href="{% url 'users:login' %}" class="nav-link">Login</a>
                {% endif %}
              </li>
            </ul>
            
          </div>
        </div>
      </nav>

      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-{{message.tags}}">

        {{message}}
      </div>
      
      {% endfor %}
      {% endif %}
      {% block body %}
      {% endblock body %}
 
    
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

templates/detail.html
{% extends 'base.html' %}


{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{item.item_image}}" class="card" style="width: 18rem;" />
        </div>
        <div class="col-md-6">
            
            <h1>{{item.item_name}}</h1>
            <h2>{{item.item_desc}}</h2>
            <h3>${{item.item_price}}</h3>
            <a href="{% url 'food:delete_item' item.id %}">Delete</a>
        </div>
    </div>

</div>


{% endblock body %}

templates/index.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Document</title>
</head>
<body>

  {% block body %}
  {% for item in item_list %}
  <div class="row">
    <div class="col-md-3 offset-md-2">
      <img class="card" style="width: 18rem;" src="{{item.item_image}}" />
    </div>
    <div class="col-md-4">
     <h3> {{item.item_name}}</h3>
     <h5>{{item.item_desc}}</h5>
     <h6>$ {{item.item_price}}</h6>
     <h6>{{item.user_name}}</h6>
    </div>
    <div class="col-md-2">
      <a href="{% url 'food:detail' item.id %}" class="btn btn-success" >Details</a>
    </div>
  </div>

  {% endfor %}
  {% endblock body %}
    <ul>
      <li>
   
    <a href="{% url 'food:detail' item.id %}"> {{item.id}} -- {{item.item_name}}</a>
       </li>
    </ul>
   
  
    
   
</body>
</html>

templates/item-delete.html
{% extends 'base.html' %}

{% block body %}
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{item.item_name}}</h2>
    <button type="submit">Confirm</button>
</form>


{% endblock body %}

templates/item-form.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type = "submit">Save</button>
</form>
{% endblock body%}

templates/login.html
{% extends 'base.html' %}


{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Login
                    </div>
                </div>
                <div class="card-body">
                                        
                    <form method="POST" autocomplete="off">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group">
                            {{field.name}}
                            {{field}}
                        </div>
                        {% endfor %}
                        <button class="btn btn-info" type="submit">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}

templates/logout.html
<h1>You have been logged out</h1>

templates/profile.html
<h1>{{user.username}}</h1>
<img src="{{user.profile.image.url}}" height="150px" />

templates/register.html
{% extends 'base.html' %}


{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Register
                    </div>
                </div>
                <div class="card-body">
                                        
                                            
                        <form method='POST'>
                            {% csrf_token %}
                            {% for field in form %}
                            <div class="form-group">
                                {{field.name}}
                                <br>
                                {{field}}
                            </div>
                            {% endfor %}
                            <button class="btn btn-info" type="submit"> Signup</button>
                        </form>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}